export const CONFIG = {
  GAME_WIDTH: 480,
  GAME_HEIGHT: 720,
  BACKGROUND_COLOR: 0x0a0a1a,
  PLAYER_SPEED: 5,
  PLAYER_SLOW_SPEED: 2,
  PLAYER_HITBOX_RADIUS: 3,
  PLAYER_LIVES: 3,
  PLAYER_BOMBS: 3,
  PLAYER_INVINCIBLE_TIME: 2000,
  BULLET_POOL_SIZE: 2000,
  PARTICLE_POOL_SIZE: 500,
  SPATIAL_HASH_CELL_SIZE: 64,
} as const;
